FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copiar archivos del frontend
COPY frontend/ .
RUN chmod -R 644 /usr/share/nginx/html/ && \
    find /usr/share/nginx/html/ -type d -exec chmod 755 {} \;


# Copiar configuración Nginx con SSL
COPY nginx-ssl.conf /etc/nginx/conf.d/default.conf

# Crear directorio para certificados (se montarán como volumen)
RUN mkdir -p /etc/letsencrypt

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
